apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Compute-api
  description: 
    API created as a component - incorrected
  links:
    - title: Website
      url: http://www.yandex.ru
    - title: Documentation
      url: http://wiki.com
    - title: Storybook
      url: http://www.yandex.ru
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: Pavellevinson/Compute_test
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: openapi
  owner: pmlevinson
  lifecycle: experimental
  system: Compute_System
